// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAaflXIKpCR_9_X7b5z8fTaotI2llrRSc',
    appId: '1:66826276753:web:c613b7aadb58636d209430',
    messagingSenderId: '66826276753',
    projectId: 'quizmasterproject-d3e93',
    authDomain: 'quizmasterproject-d3e93.firebaseapp.com',
    storageBucket: 'quizmasterproject-d3e93.firebasestorage.app',
    measurementId: 'G-95314QZHSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsNZuoWmF7iIjG48NSN4PT1NOSgdGXd5Y',
    appId: '1:66826276753:android:86f9166ed9629012209430',
    messagingSenderId: '66826276753',
    projectId: 'quizmasterproject-d3e93',
    storageBucket: 'quizmasterproject-d3e93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGNjy7HCkqgDk-etHgsLape64PK3v37U',
    appId: '1:66826276753:ios:8883903a04b76e38209430',
    messagingSenderId: '66826276753',
    projectId: 'quizmasterproject-d3e93',
    storageBucket: 'quizmasterproject-d3e93.firebasestorage.app',
    iosBundleId: 'com.quizmaster.app.quizMasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgGNjy7HCkqgDk-etHgsLape64PK3v37U',
    appId: '1:66826276753:ios:8883903a04b76e38209430',
    messagingSenderId: '66826276753',
    projectId: 'quizmasterproject-d3e93',
    storageBucket: 'quizmasterproject-d3e93.firebasestorage.app',
    iosBundleId: 'com.quizmaster.app.quizMasterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAaflXIKpCR_9_X7b5z8fTaotI2llrRSc',
    appId: '1:66826276753:web:adde0d4d8b6cb08e209430',
    messagingSenderId: '66826276753',
    projectId: 'quizmasterproject-d3e93',
    authDomain: 'quizmasterproject-d3e93.firebaseapp.com',
    storageBucket: 'quizmasterproject-d3e93.firebasestorage.app',
    measurementId: 'G-9J5NY685C0',
  );
}
